In [2]:
import numpy as np

In [4]:
mylist = [1,2,3]

In [5]:
arr = np.array(mylist)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[2,3,2],[2,1,2]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [2, 3, 2],
       [2, 1, 2]])

In [26]:
#creating numpy arrays using inbuilt genration methods or functions

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
#specific type of arrays

In [20]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [23]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
#linspace returns the evenly spcaed number over a specified interval
#you need to mention start,stop and how many numbers you need

In [38]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [39]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [41]:
#Identity matrix is a 2d square matrix(no. of rows = columns) where diagonal values are 1 and all other values are 0

In [42]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [45]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#Arrays of Random numbers

In [52]:
#uniformly distributed

In [47]:
np.random.rand(10)

array([0.15449544, 0.91062271, 0.45287424, 0.0513255 , 0.91465645,
       0.32095545, 0.79734166, 0.53004525, 0.50308605, 0.58156933])

In [48]:
np.random.rand(5,5)

array([[0.67854944, 0.30780364, 0.37029636, 0.75522007, 0.05022119],
       [0.06338915, 0.01825893, 0.98173881, 0.49161365, 0.92846693],
       [0.39323388, 0.65562088, 0.74278881, 0.89512836, 0.16137454],
       [0.33626853, 0.97413206, 0.66897647, 0.6846761 , 0.21216768],
       [0.74455824, 0.40321498, 0.60655988, 0.64204902, 0.75232376]])

In [53]:
#standard normal distribution

In [54]:
np.random.randn(2)

array([-0.3107836 ,  1.72722647])

In [55]:
np.random.randn(4,4)

array([[-0.50736878,  0.09336582,  0.5071793 , -0.11923871],
       [ 0.81326166, -0.07484299,  0.62287648,  0.25093557],
       [-0.55834059,  0.34632452,  0.01379311,  1.07557915],
       [-0.00332912,  0.53685296,  0.30827215, -0.44574065]])

In [56]:
#randint return random number from low to high

In [57]:
np.random.randint(1,100)

82

In [58]:
np.random.randint(1,100,10)

array([19, 32, 60, 29, 14, 30, 13, 70, 29, 72])

In [59]:
#Few useful attributes and methods in arrays

In [60]:
arr = np.arange(25)

In [62]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [63]:
randarr = np.random.randint(0,50,10)

In [64]:
randarr

array([38, 12, 19, 34, 22, 48, 37, 21, 23,  1])

In [68]:
#reshape method
#Note: You will get an array if you cant fill up the matrix completely 

In [69]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
randarr.reshape(5,2)

array([[38, 12],
       [19, 34],
       [22, 48],
       [37, 21],
       [23,  1]])

In [75]:
randarr.max()

48

In [80]:
randarr.min()

1

In [87]:
#to find out the index positon of max and min value

In [88]:
randarr.argmin()

9

In [94]:
arr.argmax()

24

In [99]:
arr = arr.reshape(5,5)

In [100]:
arr.shape

(5, 5)

In [102]:
arr.dtype

dtype('int64')

In [104]:
#If you import "numpy.random import randint" at the top. 
#Instead of np.random.randint(0,50,10), you can write randint(0,50,10)

In [105]:
#Numpy Array indexing

In [107]:
import numpy as np

In [108]:
arr = np.arange(0,11)

In [109]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [110]:
arr[5]

5

In [111]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [112]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [113]:
arr[0:5]= 100

In [114]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [115]:
arr= np.arange(0,11)

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
slice_of_array = arr[0:6]

In [122]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [124]:
slice_of_array[:] = 99

In [125]:
slice_of_array

array([99, 99, 99, 99, 99, 99])

In [126]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [135]:
#Note: Change has also occured in original array. Reason numpy does that to avoid memory issues in large arrays
#To avoid the values change in original arrays you can create copy of the array (arr.copy())

In [129]:
arr_copy = arr.copy()

In [130]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [131]:
arr_copy[0:5] = 10

In [132]:
arr_copy

array([10, 10, 10, 10, 10, 99,  6,  7,  8,  9, 10])

In [133]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [134]:
#Indexing in 2d array or matrix

In [137]:
arr_2d = np.array([[5,10,15],[2,4,6],[6,8,3]])

In [138]:
arr_2d

array([[ 5, 10, 15],
       [ 2,  4,  6],
       [ 6,  8,  3]])

In [143]:
arr_2d[2][1]

8

In [146]:
#Recomended notation 

In [151]:
arr_2d[2,1]

8

In [154]:
#keep in mind the row while indexing and slicing 

In [155]:
arr_2d[:2,1:]

array([[10, 15],
       [ 4,  6]])

In [156]:
arr_2d[:2]

array([[ 5, 10, 15],
       [ 2,  4,  6]])

In [157]:
#Method of selection: Condition selection

In [158]:
arr = np.arange(1,11)

In [159]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [161]:
bool_arr = arr>5

In [162]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [163]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [168]:
#Alternatively we can directly put in one line code

In [169]:
arr[arr<3]

array([1, 2])

In [178]:
arr_2d = np.arange(50).reshape(5,10)

In [179]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [182]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [185]:
arr_2d[3:5,8:10]

array([[38, 39],
       [48, 49]])

In [186]:
#Numpy operations

In [190]:
arr = np.arange(0,11)

In [191]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [192]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [193]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [196]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [195]:
#Same can be applied with the scaler(single number)

In [197]:
arr +100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [199]:
arr-10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [200]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [188]:
#Universal array fucntion

In [201]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [202]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [203]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [204]:
np.max(arr)

10

In [205]:
arr.max()

10

In [5]:
 b = np.random.randn(3,3)

In [6]:
b

array([[-1.10371116,  2.24712189,  0.37229058],
       [ 0.25959426, -0.04119237, -0.91006952],
       [ 0.0123095 , -0.63202998,  1.30510928]])